#!/bin/bash
# This script used to count the files in 2019030104.txt boxes but all
# these books have now been moved into named .txt files eg ora_classic.txt
# do not count the ebooks
rm -f allbooks
txtfiles=`ls *.txt | grep -v ebook | grep -v games_humble`
for i in $txtfiles
do
    cat $i >> allbooks
done
egrep -v '^($|#)' allbooks | grep -v 'lost?' |  wc -l

